package com.test.trainticket.model;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

/**
 * Entity mapped to table "STATION".
 */
@Entity
public class StationDao {

    @Id
    private Long id;

    @NotNull
    private String name;
    private String code;

    @Generated(hash = 1114273053)
    public StationDao() {
    }

    public StationDao(Long id) {
        this.id = id;
    }

    @Generated(hash = 1166399914)
    public StationDao(Long id, @NotNull String name, String code) {
        this.id = id;
        this.name = name;
        this.code = code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    public void setName(@NotNull String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

}
